# Generated by Django 4.2.1 on 2023-05-07 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_hackathon_created_by_alter_hackathon_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="start_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
