# Generated by Django 4.2.1 on 2023-05-10 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submissions", "0004_hackathonregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="submission_file",
            field=models.FileField(
                blank=True, null=True, upload_to="images/submissions/"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/submissions/"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                default="AnonymousUser",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
